appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: F02ZJVwE25VTrAxyMNI7syp722vay0MaiZ9GB1oMR0nTY5/Ph78aIVN5uHtV96B5NHe8GaTilwEPFFZohM6l9U4Qbzw3PN9b5n40I67gpHFzDkdBz9vjqzWD9iHjiLQE/zreA1drfwLss/QpYeSrPTb+wge4CMfSjq4b4+T+AVpmZu+5xxGEKYQUFwbSbHkWFLPuI2HVDGGIcGMPSeVygLrEttKSzxCIKCDMxFgdOtqYDxs5R87254nW0B/3uMIR8f3Wj7+BdRVnziU5lzvKPyCdXfOToNPA6amCCsO2JG8NzDX0xhz2F1Ayn4ylcFgqXmG0Y+STWKJSKH8ZTm154vgSJ+2hnPhJILjXZ6oGUAwirSoe28cMER3J13xWfV6+7DJfKUJRsICP9p7Ypjh7qfu2oj2+cg8w+CeItbzhlxhjz4cbrDoBW0hDY9xVhoPrXlPEKCpXpaUZXVOIYguKG5QaNUwoZv1QmqsM/V4Yl2WmxRz+TeEm8bzb31xBgvNdMxVmJe9GwMXOvTZyGRq8oC1l2YkQCFEVqFuCpAIU5MjPFJsQKjR0wfxxvfMnaEfQsZNMnEoLsIWhasR5GxFfnkbCg5yWMgcLH4C+hzJBefpcERX3WxUrWya6w5++AZXGUaOnYWzE3C3x0AmxWYso1+eFQK3WmKCNZDNyO7VCtmc=}
